trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ACR_NAME: 'team13acr'
  IMAGE_NAME: 'team13acrimage'
  TAG: 'latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    az login --service-principal --username "da2e9824-9e18-4bfa-bb49-1a5fa41f33a2" --password "VCe8Q~IPm~0qzKNSPYdkfL2upDhywEnFGIvvBbyE" --tenant "194208ed-3950-42f3-bc7e-5a986a5c9e55"
    az acr login --name $(ACR_NAME)
  displayName: 'Login to Azure'

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    containerRegistry: '$(ACR_NAME).azurecr.io'
    repository: '$(IMAGE_NAME)'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(TAG)'
