name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: self-hosted  # Use the self-hosted runner
    labels: [githubrunner] # Specify the runner label

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      run: |
        echo "${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}" | docker login team13acr.azurecr.io -u ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t team13acr.azurecr.io/team13week2:${{ github.run_id }} -f Dockerfile.txt .

    - name: Push Docker image
      run: |
        docker push team13acr.azurecr.io/team13week2:${{ github.run_id }}
